### ISSUE TITLE
Compatibility issue with blomstra/flarum-ext-fontawesome

### ISSUE THREAD

**Issue by iamdarkle** [clarkwinkelmann/flarum-pages-generator#2]
I'm not sure how this extension can interfere but for some reason flarum-pages-generator stops working when `blomstra/flarum-ext-fontawesome` is enabled.

**Comment by clarkwinkelmann** [comment]
The problem lies with the FontAwesome extension. It resolves `UrlGenerator` too early in a service provider, causing all extensions enabled after itself to be unable to register new routes https://github.com/blomstra/flarum-ext-fontawesome/blob/master/src/Providers/FontAwesomePreloads.php

Usually this can be worked around by disabling and re-enabling extensions in a new order, but since root `extend.php` extenders always run last, there is no workaround until this gets fixed in the Blomstra extension.

**Comment by iamdarkle** [comment]
Oh well then I guess that also explains why I'm having incompatibility problems with a couple of other extensions as well, thanks for the research! I'll open the issue on the Blomstra extension, I'll close this 🙂
